import type { MetadataRoute } from "next";

const BASE_URL = "https://medicareinfopro.com";

// ── Core pages ──────────────────────────────────────────────────────────────
const CORE_PAGES = [
  "/",
  "/what-is-medicare",
  "/medicare-advantage",
  "/medicare-supplement",
  "/medicare-part-a",
  "/medicare-part-b",
  "/medicare-part-d",
  "/original-vs-advantage",
  "/coverage",
  "/coverage-qa",
  "/blog",
  "/free-consultation",
  "/contact-us",
  "/about-us",
  "/our-team",
  "/testimonials",
  "/resources",
  "/guides",
  "/faq",
  "/faqs",
  "/plan-comparison",
  "/medicare-101",
  "/medicare-quiz",
  "/medicare-penalty-calculator",
  "/enrollment-calculator",
  "/enrollment-timeline",
  "/cost-estimator",
  "/costs-at-a-glance",
  "/maximize-benefits",
  "/still-working",
  "/am-i-eligible",
  "/do-i-need-medicare",
  "/do-i-need-a-supplement",
  "/first-steps-checklist",
  "/3-ways-to-begin-your-medicare-coverage",
  "/turning-65-and-becoming-eligible-for-medicare",
  "/hmos",
  "/medicare-snp-plans",
  "/medicare-advantage-florida",
  "/medicare-ppo-plans-in-tampa",
  "/medicare-plan-counseling-tampa",
  "/understanding-part-d",
  "/how-medicare-part-d-works",
  "/privacy-policy",
  "/terms-and-conditions",
];

// ── Coverage sub-pages ───────────────────────────────────────────────────────
const COVERAGE_PAGES = [
  "/coverage/cancer-treatment",
  "/coverage/dental",
  "/coverage/hearing-aids",
  "/coverage/medical-equipment",
  "/coverage/mental-health",
  "/coverage/physical-therapy",
  "/coverage/prescription-drugs",
  "/coverage/skilled-nursing",
  "/coverage/vision",
];

// ── Local service area pages ─────────────────────────────────────────────────
const LOCAL_PAGES = [
  "/health-insurance-apollo-beach",
  "/health-insurance-brandon",
  "/health-insurance-riverview",
  "/health-insurance-sun-city",
  "/health-insurance-valrico",
  "/health-insurance-wimauma",
  "/health-insurance-broker-apollo-beach",
  "/health-insurance-broker-brandon",
  "/health-insurance-broker-riverview",
  "/health-insurance-broker-ruskin",
  "/health-insurance-broker-temple-terrace",
  "/health-insurance-broker-valrico",
  "/medicare-agent-apollo-beach",
  "/medicare-agent-brandon",
  "/medicare-agent-riverview",
  "/medicare-agent-sun-city",
  "/medicare-agent-valrico",
  "/medicare-agent-wimauma",
  "/medicare-insurance-agent-apollo-beach-fl",
  "/medicare-insurance-agent-bartow-fl",
  "/medicare-insurance-agent-brandon-fl",
  "/medicare-insurance-agent-fish-hawk-fl",
  "/medicare-insurance-agent-gibsonton-fl",
  "/medicare-insurance-agent-lithia-fl",
  "/medicare-insurance-agent-plant-city-fl",
  "/medicare-insurance-agent-riverview-fl",
  "/medicare-insurance-agent-ruskin-fl",
  "/medicare-insurance-agent-seffner-fl",
  "/medicare-insurance-agent-sun-city-center-fl",
  "/medicare-insurance-agent-tampa-fl",
  "/medicare-insurance-agent-temple-terrace-fl",
  "/medicare-insurance-agent-valrico-fl",
  "/medicare-insurance-agent-wimauma-fl",
  "/local-medicare-agent",
  "/local-medicare-agent-apollo-beach",
  "/local-medicare-agent-plant-city",
  "/local-medicare-agent-riverview",
  "/local-medicare-agent-sun-city",
  "/local-medicare-agent-temple-terrace",
  "/local-medicare-agent-valrico",
  "/medicare-consulting-services-apollo-beach",
  "/medicare-consulting-services-bartow",
  "/medicare-consulting-services-brandon",
  "/medicare-consulting-services-fish-hawk",
  "/medicare-consulting-services-gibsonton",
  "/medicare-consulting-services-lithia",
  "/medicare-consulting-services-plant-city",
  "/medicare-consulting-services-riverview",
  "/medicare-consulting-services-ruskin",
  "/medicare-consulting-services-seffner",
  "/medicare-consulting-services-sun-city",
  "/medicare-consulting-services-sun-city-center",
  "/medicare-consulting-services-tampa",
  "/medicare-consulting-services-valrico",
  "/medicare-consulting-services-wimauma",
  "/medicare-enrollment-assistance-apollo-beach",
  "/medicare-enrollment-assistance-bartow",
  "/medicare-enrollment-assistance-brandon",
  "/medicare-enrollment-assistance-in-apollo-beach-fl",
  "/medicare-enrollment-assistance-in-brandon-fl",
  "/medicare-enrollment-assistance-in-riverview-fl",
  "/medicare-enrollment-assistance-in-sun-city-center-fl",
  "/medicare-enrollment-assistance-in-tampa-fl",
  "/medicare-enrollment-assistance-in-valrico-fl",
  "/medicare-enrollment-assistance-in-wimauma-fl",
  "/medicare-enrollment-assistance-plant-city",
  "/medicare-enrollment-assistance-riverview",
  "/medicare-enrollment-assistance-sun-city",
  "/medicare-enrollment-assistance-temple-terrace",
  "/medicare-enrollment-assistance-valrico",
  "/medicare-supplement-insurance-plans-apollo-beach",
  "/medicare-supplement-insurance-plans-bartow",
  "/medicare-supplement-insurance-plans-brandon",
  "/medicare-supplement-insurance-plans-in-brandon-fl",
  "/medicare-supplement-insurance-plans-plant-city",
  "/medicare-supplement-insurance-plans-riverview",
  "/medicare-supplement-insurance-plans-sun-city",
  "/medicare-supplement-insurance-plans-tampa",
  "/medicare-supplement-insurance-plans-temple-terrace",
  "/medicare-supplement-insurance-plans-valrico",
  "/trusted-medicare-insurance-agent-health-insurance-services-apollo-beach",
  "/trusted-medicare-insurance-agent-health-insurance-services-brandon",
  "/trusted-medicare-insurance-agent-health-insurance-services-riverview",
  "/trusted-medicare-insurance-agent-health-insurance-services-sun-city",
  "/trusted-medicare-insurance-agent-health-insurance-services-temple-terrace",
  "/trusted-medicare-insurance-agent-health-insurance-services-valrico",
  "/trusted-medicare-insurance-brokers-apollo-beach",
  "/trusted-medicare-insurance-brokers-brandon",
  "/trusted-medicare-insurance-brokers-riverview",
  "/trusted-medicare-insurance-brokers-ruskin",
  "/trusted-medicare-insurance-brokers-valrico",
  "/trusted-medicare-insurance-brokers-wimauma",
  "/comparing-medicare-plans-apollo-beach",
  "/comparing-medicare-plans-brandon",
  "/comparing-medicare-plans-plant-city",
  "/comparing-medicare-plans-riverview",
  "/comparing-medicare-plans-valrico",
  "/medicare-advantage-plans-brandon-florida",
  "/medicare-part-b-assistance-in-brandon",
  "/tampa-medicare-specialist",
];

// ── Team / advisor pages ─────────────────────────────────────────────────────
const TEAM_PAGES = [
  "/advisors",
  "/find-an-agent",
  "/greg-wohl",
  "/jennifer-loader-wohl",
  "/chris-gallimore",
  "/paul-eckstein",
  "/dutch-vanhoesen",
  "/mark-vanhoesen",
  "/jd-diaz",
  "/kelly-webb",
  "/paxton-dement",
  "/valerie-justin-hall",
];

// ── Blog articles ────────────────────────────────────────────────────────────
const BLOG_SLUGS = [
  "/blog/does-medicare-cover-home-health-care",
  "/blog/what-is-the-special-enrollment-period",
  "/blog/does-medicare-cover-cataract-surgery",
  "/blog/does-medicare-cover-ambulance-rides",
  "/blog/why-is-health-insurance-so-expensive-in-florida",
  "/blog/how-much-does-health-insurance-cost-per-month-in-florida",
  "/blog/what-are-the-best-medicare-plans-for-seniors",
  "/blog/is-reinstating-a-part-d-plan-possible",
  "/blog/best-medicare-advantage-plans-florida",
  "/blog/how-to-sign-up-for-medicare-without-an-agent-step-by-step-guide",
  "/blog/medicare-qualifications-florida",
  "/blog/how-to-reduce-medicare-premiums-based-on-income-2026",
  "/blog/medicare-advantage-changes-2026-florida",
  "/blog/medicare-set-aside-explained",
  "/blog/florida-medicare-if-still-working-at-65",
  "/blog/does-medicare-cover-ozempic",
  "/blog/switch-medicare-advantage-florida",
  "/blog/medicare-coverage-for-scooters",
  "/blog/how-medicare-premiums-are-calculated",
  "/blog/why-is-medicare-coverage-so-important",
  "/blog/can-i-drop-my-medicare-advantage-plan-and-go-back-to-original-medicare",
  "/blog/florida-health-insurance-cost",
  "/blog/medicare-plans-cancer-treatment",
  "/blog/medicare-scams-florida",
  "/blog/medicare-supplement-plans-in-florida",
  "/blog/how-to-choose-medicare-advantage-plans-2026",
  "/blog/original-medicare-vs-medicare-advantage-in-florida",
  "/blog/pros-and-cons-of-florida-medicare-supplement-plans",
  "/blog/medicare-age",
  "/blog/the-pros-and-cons-of-enrolling-in-a-medicare-advantage-plan-in-florida",
  "/blog/medicare-supplement-plans-florida-2026",
  "/blog/medicare-disability-eligibility-requirements",
  "/blog/medicare-issues-for-veterans-tampa",
  "/blog/medicare-why-are-there-so-many-letters",
  "/blog/value-added-benefits-through-medicare-advantage",
  "/blog/medigap-premium-increases",
  "/blog/why-medicare-denies-mobility-scooter-claims-florida",
  "/blog/best-medicare-agent-in-florida",
  "/blog/5-best-medicare-consultants-in-tampa-bay",
  "/blog/maximize-medicare-benefits-florida-seniors",
  "/blog/medicare-advantage-travel-benefits-florida-residents",
  "/blog/best-medicare-plans-for-snowbirds-in-florida",
  "/blog/can-i-have-both-medicare-and-medicaid",
  "/blog/medicare-part-d-out-of-pocket-cap",
  "/blog/resolving-common-challenges-when-selecting-medicare-in-florida",
  "/blog/medicare-and-employer-insurance-after-65-brandon-fl",
  "/blog/understanding-medicare-part-b",
  "/blog/which-medicare-advantage-plans-tampa-free-post-hospital-meals",
  "/blog/do-you-need-to-work-with-a-medicare-insurance-agent",
  "/blog/what-are-the-6-things-medicare-doesnt-cover",
  "/blog/medicare-broker-vs-agent",
  "/blog/affordable-health-insurance-options-for-tampa-families",
  "/blog/use-medicare-insurance-agent-in-florida",
  "/blog/plan-g-complete-guide",
  "/blog/working-past-65",
  "/blog/medicare-without-social-security",
  "/blog/why-choose-medigap-plan-g",
  "/blog/does-medicare-cover-life-alert",
  "/blog/2026-medicare-advantage-changes",
  "/blog/irmaa-explained",
  "/blog/part-d-2000-cap",
  "/blog/medigap-open-enrollment",
  "/blog/annual-enrollment-period-guide",
  "/blog/medicare-vs-medicaid",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date().toISOString();

  return [
    ...CORE_PAGES.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: (path === "/" ? "weekly" : "monthly") as "weekly" | "monthly",
      priority: path === "/" ? 1.0 : path.includes("free-consultation") ? 0.9 : 0.8,
    })),
    ...COVERAGE_PAGES.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...LOCAL_PAGES.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    })),
    ...TEAM_PAGES.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    })),
    ...BLOG_SLUGS.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
  ];
}
